version: '3.8'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=auto # specify your server's public IP or domain
      - SERVERPORT=51820
      - PEERS=1 # number of peers (clients)
      - PEERDNS=auto
    volumes:
      - ./config:/config
    ports:
      - 51820:51820/udp
    restart: unless-stopped
  management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn-management
    ports:
      - 5010:5000
    volumes:
      - ./config:/config
    restart: unless-stopped
